/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Riddho
 */
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
public class Dashboard_S extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard_S
     */
    public int status;
    public String uid;
    public int flag1,flag2,flag3;
    public int qstatus;
    public int qmax,qmaximum,qMaximum;
    public int quesno=1;
    public int score=0;
    public String correcta="",choice="";
    public String teacherid;
    public boolean tf;
    public Dashboard_S() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        sidepane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Sname = new javax.swing.JLabel();
        UID = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Home = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TT = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        VS = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        SETTING = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        LG = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        upper_panel = new javax.swing.JPanel();
        Parent = new javax.swing.JPanel();
        home = new javax.swing.JPanel();
        Settings = new javax.swing.JPanel();
        Settings1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        CP = new javax.swing.JTextField();
        NP = new javax.swing.JTextField();
        CNP = new javax.swing.JTextField();
        Submitp = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        CU = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        NU = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        CNU = new javax.swing.JTextField();
        Submitu = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        View_Scores = new javax.swing.JPanel();
        View_Scr = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        VST = new javax.swing.JTable();
        Take_Test = new javax.swing.JPanel();
        TakeTest = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        QNUM = new javax.swing.JTextField();
        QUES = new javax.swing.JTextField();
        SUBMIT = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        OPTA = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        OPTB = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        OPTC = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        OPTD = new javax.swing.JTextField();
        SA = new javax.swing.JRadioButton();
        SB = new javax.swing.JRadioButton();
        SC = new javax.swing.JRadioButton();
        SD = new javax.swing.JRadioButton();
        NEXT = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        QIDS = new javax.swing.JComboBox<>();
        STARTQ = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sidepane.setBackground(new java.awt.Color(6, 18, 111));
        sidepane.setPreferredSize(new java.awt.Dimension(210, 530));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_student_male_100px.png"))); // NOI18N

        Sname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Sname.setForeground(new java.awt.Color(255, 255, 255));
        Sname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Sname.setText("Benjamin Johnson");

        UID.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        UID.setForeground(new java.awt.Color(255, 255, 255));
        UID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UID.setText("T100");

        Home.setBackground(new java.awt.Color(6, 18, 111));
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HomeMouseExited(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_home_30px.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Home");

        javax.swing.GroupLayout HomeLayout = new javax.swing.GroupLayout(Home);
        Home.setLayout(HomeLayout);
        HomeLayout.setHorizontalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HomeLayout.setVerticalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        TT.setBackground(new java.awt.Color(6, 18, 111));
        TT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TTMouseExited(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_book_and_pencil_30px.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Take Test");

        javax.swing.GroupLayout TTLayout = new javax.swing.GroupLayout(TT);
        TT.setLayout(TTLayout);
        TTLayout.setHorizontalGroup(
            TTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TTLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TTLayout.setVerticalGroup(
            TTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        VS.setBackground(new java.awt.Color(6, 18, 111));
        VS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VSMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VSMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VSMouseExited(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_trophy_30px.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("View Scores");

        javax.swing.GroupLayout VSLayout = new javax.swing.GroupLayout(VS);
        VS.setLayout(VSLayout);
        VSLayout.setHorizontalGroup(
            VSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VSLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        VSLayout.setVerticalGroup(
            VSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        SETTING.setBackground(new java.awt.Color(6, 18, 111));
        SETTING.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SETTINGMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SETTINGMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SETTINGMouseExited(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_settings_30px.png"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Settings");

        javax.swing.GroupLayout SETTINGLayout = new javax.swing.GroupLayout(SETTING);
        SETTING.setLayout(SETTINGLayout);
        SETTINGLayout.setHorizontalGroup(
            SETTINGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SETTINGLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SETTINGLayout.setVerticalGroup(
            SETTINGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        LG.setBackground(new java.awt.Color(6, 18, 111));
        LG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LGMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LGMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LGMouseExited(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_exit_30px.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Logout");

        javax.swing.GroupLayout LGLayout = new javax.swing.GroupLayout(LG);
        LG.setLayout(LGLayout);
        LGLayout.setHorizontalGroup(
            LGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LGLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LGLayout.setVerticalGroup(
            LGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout sidepaneLayout = new javax.swing.GroupLayout(sidepane);
        sidepane.setLayout(sidepaneLayout);
        sidepaneLayout.setHorizontalGroup(
            sidepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(TT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(VS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(SETTING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sidepaneLayout.createSequentialGroup()
                .addGroup(sidepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidepaneLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(sidepaneLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
            .addComponent(Sname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(UID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sidepaneLayout.setVerticalGroup(
            sidepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidepaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Sname)
                .addGap(0, 0, 0)
                .addComponent(UID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(VS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SETTING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        upper_panel.setBackground(new java.awt.Color(6, 18, 111));

        javax.swing.GroupLayout upper_panelLayout = new javax.swing.GroupLayout(upper_panel);
        upper_panel.setLayout(upper_panelLayout);
        upper_panelLayout.setHorizontalGroup(
            upper_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        upper_panelLayout.setVerticalGroup(
            upper_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );

        Parent.setPreferredSize(new java.awt.Dimension(720, 514));
        Parent.setLayout(new java.awt.CardLayout());

        home.setBackground(new java.awt.Color(153, 255, 153));

        javax.swing.GroupLayout homeLayout = new javax.swing.GroupLayout(home);
        home.setLayout(homeLayout);
        homeLayout.setHorizontalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        homeLayout.setVerticalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 514, Short.MAX_VALUE)
        );

        Parent.add(home, "card2");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(54, 33, 89));
        jLabel9.setText("Settings");

        jPanel1.setBackground(new java.awt.Color(6, 18, 111));
        jPanel1.setForeground(new java.awt.Color(54, 33, 89));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_lock_25px_1.png"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("CHANGE PASSWORD");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(6, 18, 111));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_user_shield_25px_1.png"))); // NOI18N

        jLabel16.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("CHANGE USERID");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(54, 33, 89));
        jLabel17.setText("Current Password:");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(54, 33, 89));
        jLabel18.setText("New Password:");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(54, 33, 89));
        jLabel19.setText("Confirm New Password:");

        Submitp.setBackground(new java.awt.Color(6, 18, 111));
        Submitp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SubmitpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SubmitpMouseExited(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Submit");

        javax.swing.GroupLayout SubmitpLayout = new javax.swing.GroupLayout(Submitp);
        Submitp.setLayout(SubmitpLayout);
        SubmitpLayout.setHorizontalGroup(
            SubmitpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        SubmitpLayout.setVerticalGroup(
            SubmitpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(54, 33, 89));
        jLabel21.setText("Current UserID:");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(54, 33, 89));
        jLabel22.setText("New UserID:");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(54, 33, 89));
        jLabel23.setText("Confirm New UserID:");

        Submitu.setBackground(new java.awt.Color(6, 18, 111));
        Submitu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmituMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SubmituMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SubmituMouseExited(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Submit");

        javax.swing.GroupLayout SubmituLayout = new javax.swing.GroupLayout(Submitu);
        Submitu.setLayout(SubmituLayout);
        SubmituLayout.setHorizontalGroup(
            SubmituLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        SubmituLayout.setVerticalGroup(
            SubmituLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Settings1Layout = new javax.swing.GroupLayout(Settings1);
        Settings1.setLayout(Settings1Layout);
        Settings1Layout.setHorizontalGroup(
            Settings1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Settings1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel9)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(Settings1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Settings1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(68, 68, 68))
            .addGroup(Settings1Layout.createSequentialGroup()
                .addGroup(Settings1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Settings1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(Settings1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(58, 58, 58)
                        .addGroup(Settings1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NP)
                            .addComponent(CNP, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                            .addComponent(CP, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(Settings1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(Settings1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Settings1Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(34, 34, 34)
                                .addComponent(CNU, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Settings1Layout.createSequentialGroup()
                                .addGroup(Settings1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel21))
                                .addGap(34, 34, 34)
                                .addGroup(Settings1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NU, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CU, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Settings1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Settings1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Settings1Layout.createSequentialGroup()
                        .addComponent(Submitp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(221, 221, 221))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Settings1Layout.createSequentialGroup()
                        .addComponent(Submitu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(222, 222, 222))))
        );
        Settings1Layout.setVerticalGroup(
            Settings1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Settings1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(Settings1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(CP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Settings1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(NP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(Settings1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(CNP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Submitp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(Settings1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(CU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Settings1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(18, 18, 18)
                .addGroup(Settings1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(CNU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Submitu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout SettingsLayout = new javax.swing.GroupLayout(Settings);
        Settings.setLayout(SettingsLayout);
        SettingsLayout.setHorizontalGroup(
            SettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
            .addGroup(SettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Settings1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SettingsLayout.setVerticalGroup(
            SettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 514, Short.MAX_VALUE)
            .addGroup(SettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Settings1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Parent.add(Settings, "card5");

        View_Scores.setBackground(new java.awt.Color(255, 0, 102));

        jLabel49.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(6, 18, 111));
        jLabel49.setText("View Scores");

        VST.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        VST.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "QuizID", "Teacher ID", "Score"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        VST.getTableHeader().setReorderingAllowed(false);
        VST.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VSTMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(VST);

        javax.swing.GroupLayout View_ScrLayout = new javax.swing.GroupLayout(View_Scr);
        View_Scr.setLayout(View_ScrLayout);
        View_ScrLayout.setHorizontalGroup(
            View_ScrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(View_ScrLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel49)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, View_ScrLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator5)
                .addGap(68, 68, 68))
            .addGroup(View_ScrLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                .addContainerGap())
        );
        View_ScrLayout.setVerticalGroup(
            View_ScrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(View_ScrLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel49)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout View_ScoresLayout = new javax.swing.GroupLayout(View_Scores);
        View_Scores.setLayout(View_ScoresLayout);
        View_ScoresLayout.setHorizontalGroup(
            View_ScoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
            .addGroup(View_ScoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(View_Scr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        View_ScoresLayout.setVerticalGroup(
            View_ScoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 514, Short.MAX_VALUE)
            .addGroup(View_ScoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(View_Scr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Parent.add(View_Scores, "card4");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(6, 18, 111));
        jLabel25.setText("Take Test");

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(6, 18, 111));
        jLabel30.setText("Quiz ID:");

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(6, 18, 111));
        jLabel31.setText("Question No.");

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(6, 18, 111));
        jLabel32.setText("Question:");

        QNUM.setEditable(false);

        QUES.setEditable(false);

        SUBMIT.setBackground(new java.awt.Color(6, 18, 111));
        SUBMIT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SUBMITMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SUBMITMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SUBMITMouseExited(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("Submit");
        jLabel33.setPreferredSize(new java.awt.Dimension(119, 28));

        javax.swing.GroupLayout SUBMITLayout = new javax.swing.GroupLayout(SUBMIT);
        SUBMIT.setLayout(SUBMITLayout);
        SUBMITLayout.setHorizontalGroup(
            SUBMITLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SUBMITLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        SUBMITLayout.setVerticalGroup(
            SUBMITLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(6, 18, 111));
        jLabel34.setText("A.");

        OPTA.setEditable(false);

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(6, 18, 111));
        jLabel35.setText("B.");

        OPTB.setEditable(false);

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(6, 18, 111));
        jLabel36.setText("C.");

        OPTC.setEditable(false);

        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(6, 18, 111));
        jLabel38.setText("D.");

        OPTD.setEditable(false);

        buttonGroup1.add(SA);
        SA.setSelected(true);

        buttonGroup1.add(SB);
        SB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SBActionPerformed(evt);
            }
        });

        buttonGroup1.add(SC);

        buttonGroup1.add(SD);

        NEXT.setBackground(new java.awt.Color(6, 18, 111));
        NEXT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NEXTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NEXTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NEXTMouseExited(evt);
            }
        });

        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("Next");

        javax.swing.GroupLayout NEXTLayout = new javax.swing.GroupLayout(NEXT);
        NEXT.setLayout(NEXTLayout);
        NEXTLayout.setHorizontalGroup(
            NEXTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel39, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
        );
        NEXTLayout.setVerticalGroup(
            NEXTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel39, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        STARTQ.setBackground(new java.awt.Color(6, 18, 111));
        STARTQ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                STARTQMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                STARTQMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                STARTQMouseExited(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Start Quiz");

        javax.swing.GroupLayout STARTQLayout = new javax.swing.GroupLayout(STARTQ);
        STARTQ.setLayout(STARTQLayout);
        STARTQLayout.setHorizontalGroup(
            STARTQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        STARTQLayout.setVerticalGroup(
            STARTQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(STARTQLayout.createSequentialGroup()
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout TakeTestLayout = new javax.swing.GroupLayout(TakeTest);
        TakeTest.setLayout(TakeTestLayout);
        TakeTestLayout.setHorizontalGroup(
            TakeTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TakeTestLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel25)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TakeTestLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TakeTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(TakeTestLayout.createSequentialGroup()
                        .addGroup(TakeTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TakeTestLayout.createSequentialGroup()
                                .addGroup(TakeTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel32)
                                    .addComponent(jLabel31)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel34)
                                    .addComponent(jLabel35)
                                    .addComponent(jLabel36))
                                .addGap(26, 26, 26)
                                .addGroup(TakeTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(TakeTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(SD)
                                        .addGroup(TakeTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, TakeTestLayout.createSequentialGroup()
                                                .addComponent(OPTC, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                                                .addComponent(SC))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, TakeTestLayout.createSequentialGroup()
                                                .addComponent(OPTB, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(SB))
                                            .addGroup(TakeTestLayout.createSequentialGroup()
                                                .addComponent(OPTA, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(SA))))
                                    .addComponent(QUES, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(TakeTestLayout.createSequentialGroup()
                                        .addGroup(TakeTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(QIDS, 0, 88, Short.MAX_VALUE)
                                            .addComponent(QNUM))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(STARTQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12))))
                            .addGroup(TakeTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(TakeTestLayout.createSequentialGroup()
                                    .addComponent(jLabel38)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 491, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TakeTestLayout.createSequentialGroup()
                                    .addGap(95, 95, 95)
                                    .addGroup(TakeTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(TakeTestLayout.createSequentialGroup()
                                            .addComponent(NEXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(SUBMIT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(OPTD, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 20, Short.MAX_VALUE))
                    .addComponent(jSeparator3))
                .addGap(68, 68, 68))
        );
        TakeTestLayout.setVerticalGroup(
            TakeTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TakeTestLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(TakeTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TakeTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel30)
                        .addComponent(QIDS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(STARTQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(TakeTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(QNUM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(TakeTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(TakeTestLayout.createSequentialGroup()
                        .addGroup(TakeTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(QUES, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32))
                        .addGap(53, 53, 53)
                        .addGroup(TakeTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SA)
                            .addGroup(TakeTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel34)
                                .addComponent(OPTA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31)
                        .addGroup(TakeTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SB)
                            .addGroup(TakeTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel35)
                                .addComponent(OPTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(36, 36, 36)
                        .addGroup(TakeTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SC)
                            .addGroup(TakeTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel36)
                                .addComponent(OPTC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34)
                        .addGroup(TakeTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel38)
                            .addComponent(OPTD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(SD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(TakeTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SUBMIT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NEXT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout Take_TestLayout = new javax.swing.GroupLayout(Take_Test);
        Take_Test.setLayout(Take_TestLayout);
        Take_TestLayout.setHorizontalGroup(
            Take_TestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
            .addGroup(Take_TestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(TakeTest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Take_TestLayout.setVerticalGroup(
            Take_TestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 514, Short.MAX_VALUE)
            .addGroup(Take_TestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(TakeTest, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Parent.add(Take_Test, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidepane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(upper_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Parent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidepane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(upper_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Parent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void removeCombo()
    {
    int itemCount = QIDS.getItemCount();

    for(int i=0;i<itemCount;i++){
        QIDS.removeItemAt(0);
     }
    
    
    }
    public String getChoice()
    {
    if(SA.isSelected()==true)
    {   
     return OPTA.getText();
    }   
    if(SB.isSelected()==true)
    {   
     return OPTB.getText();
    }   
    if(SB.isSelected()==true)
    {   
     return OPTB.getText();
    }   
    if(SC.isSelected()==true)
    {   
     return OPTC.getText();
    }   
    if(SD.isSelected()==true)
    {   
     return OPTD.getText();
    }   
        return null;
    }
    
    public int getMaximum()
{
    try
    {
        Class.forName("java.sql.DriverManager");
          Connection cMaximum=(Connection)DriverManager.getConnection("jdbc:Mysql://localhost:3306/quiz","root","root");
          Statement sMaximum=(Statement)cMaximum.createStatement();
          String qMaxim="select max(qnu) from quiz where qid='"+QIDS.getSelectedItem().toString()+"';";
          ResultSet rMaximum=sMaximum.executeQuery(qMaxim);
          if(rMaximum.next())
          {
           qmaximum=rMaximum.getInt("max(qnu)");
          }
          }
        catch(ClassNotFoundException | SQLException e)
        {
        JOptionPane.showMessageDialog(this,e);
        }
        return qmaximum;
        }  
    public void StoreScore(int scr)
    {
      try
      {
          Class.forName("java.sql.DriverManager");
          Connection cstore=(Connection)DriverManager.getConnection("jdbc:Mysql://localhost:3306/quiz","root","root");
          Statement sstore=(Statement)cstore.createStatement();
          String findteacher="select distinct tid from quiz where qid='"+QIDS.getSelectedItem().toString()+"';";
          ResultSet rfindteacher=sstore.executeQuery(findteacher);
          if(rfindteacher.next())
          {
            teacherid=rfindteacher.getString("tid");
          }
          
          String qstore="insert into scores values('"+QIDS.getSelectedItem().toString()+"','"+teacherid+"','"+UID.getText()+"','"+Sname.getText()+"',"+scr+");";
          sstore.executeUpdate(qstore);
      }
    catch(ClassNotFoundException | SQLException e)
    {    
      JOptionPane.showMessageDialog(this,e);
    }
    }
   public void Clear()
   {        
    QNUM.setText("");
    QUES.setText("");
    OPTA.setText("");
    OPTB.setText("");
    OPTC.setText("");
    OPTD.setText("");
    CP.setText("");
    NP.setText("");
    CNP.setText("");
    CU.setText("");
    NU.setText("");
    CNU.setText("");
    qstatus=0;
    QIDS.setEnabled(true);
   }
   public boolean IsOccupied()
   {        
     
       try
       {
          Class.forName("java.sql.DriverManager");
          Connection cOcc=(Connection)DriverManager.getConnection("jdbc:Mysql://localhost:3306/quiz","root","root");
          Statement sOcc=(Statement)cOcc.createStatement();
          String qOcc="select*from scores where qid='"+QIDS.getSelectedItem().toString()+"' and sid='"+UID.getText()+"';";
          ResultSet rOcc=sOcc.executeQuery(qOcc);
          if(rOcc.next())
          {
           tf=true;   
          }  
          else
          {
            tf=false;
          }
       }
      catch(ClassNotFoundException | SQLException e)
      {    
        JOptionPane.showMessageDialog(this,e);
      }
       return tf;
   }   
   
   public void UpdateScore(int scre)
   {        
   try
   {
      Class.forName("java.sql.DriverManager");
      Connection cups=(Connection)DriverManager.getConnection("jdbc:Mysql://localhost:3306/quiz","root","root");
      Statement sups=(Statement)cups.createStatement();
      String qups="update scores set score="+scre+" where qid='"+QIDS.getSelectedItem().toString()+"' and sid='"+UID.getText()+"';";
     sups.executeUpdate(qups);
    }
   catch(ClassNotFoundException | SQLException e)
   {    
     JOptionPane.showMessageDialog(this,e);
   }   
   }
   public void sfetch()
   {         
     try
     {    
       Class.forName("java.sql.DriverManager");
      Connection csfetch=(Connection)DriverManager.getConnection("jdbc:Mysql://localhost:3306/quiz","root","root");
      Statement ssfetch=(Statement)csfetch.createStatement();
      String qsfetch="select qid 'QuizID',tid 'Teacher ID',score 'Score' from scores where sid='"+UID.getText()+"';";
      ResultSet rsfetch=ssfetch.executeQuery(qsfetch);
      VST.setModel(DbUtils.resultSetToTableModel(rsfetch));
      }
     catch(ClassNotFoundException | SQLException e)
     {
         JOptionPane.showMessageDialog(this,e);         
     }     
     
     
   
   }
    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
        status =1;
        Home.setBackground(new Color(89,120,224));
        VS.setBackground(new Color(6,18,111));
        SETTING.setBackground(new Color(6,18,111));
        TT.setBackground(new Color(6,18,111));
        Parent.removeAll();
        Parent.add(home);
        Parent.repaint();
        Parent.revalidate();
        Clear();
        removeCombo();
        
    }//GEN-LAST:event_HomeMouseClicked

    private void HomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseEntered
        Home.setBackground(new Color(89,120,224));
    }//GEN-LAST:event_HomeMouseEntered

    private void HomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseExited
        if(status!=1)
        {
            Home.setBackground(new Color(6,18,111));
        }
    }//GEN-LAST:event_HomeMouseExited

    private void TTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TTMouseClicked
        status=2;
        TT.setBackground(new Color(89,120,224));
        Home.setBackground(new Color(6,18,111));
        SETTING.setBackground(new Color(6,18,111));
        VS.setBackground(new Color(6,18,111));
        Parent.removeAll();
        Parent.add(Take_Test);
        Parent.repaint();
        Parent.revalidate();
        removeCombo();
        try
        {
          Class.forName("java.sql.DriverManager");
          Connection cgetT=(Connection)DriverManager.getConnection("jdbc:Mysql://localhost:3306/quiz","root","root");
          Statement sgetT=(Statement)cgetT.createStatement();
          String sget="select distinct qid from quiz;";
          ResultSet rgetT=sgetT.executeQuery(sget);
          while(rgetT.next())
          {
          String ids=rgetT.getString("qid");
          QIDS.addItem(ids);
          }
          flag3=1;
          cgetT.close();
          }
        catch(ClassNotFoundException | SQLException e)
        {
        JOptionPane.showMessageDialog(this,e);
        }
        qstatus=0;
      
    }//GEN-LAST:event_TTMouseClicked

    private void TTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TTMouseEntered
        TT.setBackground(new Color(89,120,224));
    }//GEN-LAST:event_TTMouseEntered

    private void TTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TTMouseExited
        if(status!=2)
        TT.setBackground(new Color(6,18,111));
    }//GEN-LAST:event_TTMouseExited

    private void VSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VSMouseClicked
        status=3;
        VS.setBackground(new Color(89,120,224));
        Home.setBackground(new Color(6,18,111));
        SETTING.setBackground(new Color(6,18,111));
        TT.setBackground(new Color(6,18,111));
        Parent.removeAll();
        Parent.add(View_Scores);
        Parent.repaint();
        Parent.revalidate(); 
        sfetch();
         Clear();
        removeCombo();  

         
         
         
         
         
// TODO add your handling code here:
    }//GEN-LAST:event_VSMouseClicked

    private void VSMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VSMouseEntered
        VS.setBackground(new Color(89,120,224));
    }//GEN-LAST:event_VSMouseEntered

    private void VSMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VSMouseExited
        if(status!=3)
        VS.setBackground(new Color(6,18,111));
    }//GEN-LAST:event_VSMouseExited

    private void SETTINGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SETTINGMouseClicked
        status=4;
        SETTING.setBackground(new Color(89,120,224));
        VS.setBackground(new Color(6,18,111));
        Home.setBackground(new Color(6,18,111));
        TT.setBackground(new Color(6,18,111));
        Parent.removeAll();
        Parent.add(Settings);
        Parent.repaint();
        Parent.revalidate();
        Clear();
        removeCombo();
    }//GEN-LAST:event_SETTINGMouseClicked

    private void SETTINGMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SETTINGMouseEntered
        SETTING.setBackground(new Color(89,120,224));
    }//GEN-LAST:event_SETTINGMouseEntered

    private void SETTINGMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SETTINGMouseExited
        if(status!=4)
        SETTING.setBackground(new Color(6,18,111));
    }//GEN-LAST:event_SETTINGMouseExited

    private void LGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LGMouseClicked
        int a;
        a = JOptionPane.showConfirmDialog(this,"Are you sure you want to log out ?");
        if(a==0){
            dispose();
            Login lo=new Login();
            lo.show();
        }
    }//GEN-LAST:event_LGMouseClicked

    private void LGMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LGMouseEntered
        LG.setBackground(new Color(89,120,224));
    }//GEN-LAST:event_LGMouseEntered

    private void LGMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LGMouseExited
        LG.setBackground(new Color(6,18,111));
    }//GEN-LAST:event_LGMouseExited

    private void SubmitpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitpMouseClicked
        flag1=1;
        uid=UID.getText();
        try 
        {
            Class.forName("java.sql.DriverManager");
            Connection co=(Connection)DriverManager.getConnection("jdbc:Mysql://localhost:3306/quiz","root","root");
            Statement su=(Statement)co.createStatement();
            String q="select password from details where userid='"+uid+"';";
            ResultSet r1=su.executeQuery(q);
            r1.next();
         
        if(r1.getString(1).equals(CP.getText())==false)

                {
                    JOptionPane.showMessageDialog(this,"Current Password is incorrect");
                    flag1=0;

                }

           
        
        else if(CP.getText().equals("") || NP.getText().equals("") || CNP.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Missing fields");
            flag1=0;

        }
        else if(NP.getText().equals(CNP.getText())==false)
        {
            JOptionPane.showMessageDialog(this,"New passwords do not match");
            flag1=0;
        }
        if(flag1!=0)
        {
            String np=NP.getText();

            try {
                Class.forName("java.sql.DriverManager");
                Connection connection=(Connection)DriverManager.getConnection("jdbc:Mysql://localhost:3306/quiz","root","root");
                Statement statement=(Statement)connection.createStatement();
                String q2="update details set password='"+np+"'where userid='"+uid+"';";
                statement.executeUpdate(q2);

                JOptionPane.showMessageDialog(this,"Changes Saved");
                CP.setText("");
                NP.setText("");
                CNP.setText("");
            }

            catch(HeadlessException | ClassNotFoundException | SQLException e){
                JOptionPane.showMessageDialog(this,e);
            }

        }
        }
         catch(HeadlessException | ClassNotFoundException | SQLException e){
            JOptionPane.showMessageDialog(this,e);
        }
        

        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitpMouseClicked

    private void SubmituMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmituMouseClicked
     flag2=1;

        String nu=NU.getText();

        if(UID.getText().equals(CU.getText())==false)
        {
            JOptionPane.showMessageDialog(this,"Current UserId is incorrect");
            flag2=0;
        }
        else if(CU.getText().equals("") || NU.getText().equals("") || CNU.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Please ensure all fields are entered before submitting");
              flag2=0;
        }
        else if(NU.getText().equals(CNU.getText())==false)
        {
            JOptionPane.showMessageDialog(this,"New userid's do not match");
              flag2=0;
        }
        if(flag2!=0)
        {
            try {
                Class.forName("java.sql.DriverManager");
                Connection connection2=(Connection)DriverManager.getConnection("jdbc:Mysql://localhost:3306/quiz","root","root");
                Statement statement2=(Statement)connection2.createStatement();
                String q3="update details set userid='"+nu+"'where userid='"+CU.getText()+"';";
                statement2.executeUpdate(q3);
                JOptionPane.showMessageDialog(this,"Changes Saved");
                UID.setText(nu);
                CU.setText("");
                NU.setText("");
                CNU.setText("");
            }

            catch(HeadlessException | ClassNotFoundException | SQLException e){
                JOptionPane.showMessageDialog(this,e);
            }

        }

    }//GEN-LAST:event_SubmituMouseClicked

    private void SubmitpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitpMouseEntered
Submitp.setBackground(new Color(89,120,224));        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitpMouseEntered

    private void SubmituMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmituMouseEntered
Submitu.setBackground(new Color(89,120,224));        // TODO add your handling code here:
    }//GEN-LAST:event_SubmituMouseEntered

    private void SubmitpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitpMouseExited
Submitp.setBackground(new Color(6,18,111));        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitpMouseExited

    private void SubmituMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmituMouseExited
Submitu.setBackground(new Color(6,18,111));         // TODO add your handling code here:
    }//GEN-LAST:event_SubmituMouseExited

    private void SUBMITMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SUBMITMouseClicked
if(qstatus==1)
{
      qMaximum=getMaximum();
      if(Integer.parseInt(QNUM.getText())==qMaximum )
      {   
        try
           {
           Class.forName("java.sql.DriverManager");
           Connection cfinal=(Connection)DriverManager.getConnection("jdbc:Mysql://localhost:3306/quiz","root","root");
           Statement sfinal=(Statement)cfinal.createStatement();
           String qfinal="select correct from quiz where qid='"+QIDS.getSelectedItem().toString()+"' and qnu="+qMaximum+";";
           ResultSet rfinal=sfinal.executeQuery(qfinal);
           choice=getChoice();
           if(rfinal.next())
           {
             if(rfinal.getString("correct").equals(choice))
             {
             score=score+1;
             }    
           }
           JOptionPane.showMessageDialog(this,"Your final score is:"+score);
           if(IsOccupied()==false)
           { 
          StoreScore(score);
           }
           else
           {
            UpdateScore(score); 
           }
            qstatus=0;
            QIDS.setEnabled(true);
            QNUM.setText("");
            QUES.setText("");
            OPTA.setText("");
            OPTB.setText("");
            OPTC.setText("");
            OPTD.setText("");
           }
          catch(ClassNotFoundException | SQLException e)
          {   
          JOptionPane.showMessageDialog(this,e);
          } 
      } 
      
      
      else
      {
          JOptionPane.showMessageDialog(this,"Quiz cannot be submitted before all the questions are attempted");
      }
}
else
{
JOptionPane.showMessageDialog(this,"Quiz has not started yet");
}
    }//GEN-LAST:event_SUBMITMouseClicked

    private void SUBMITMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SUBMITMouseEntered
       SUBMIT.setBackground(new Color(89,120,224));     // TODO add your handling code here:
    }//GEN-LAST:event_SUBMITMouseEntered

    private void SUBMITMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SUBMITMouseExited
     SUBMIT.setBackground(new Color(6,18,111));    // TODO add your handling code here:
    }//GEN-LAST:event_SUBMITMouseExited

    private void NEXTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NEXTMouseClicked
if(qstatus==1)//checking if quiz is currently active or not
{   
      try  //block for calculating max(qnu) i.e. last question number
      {
      Class.forName("java.sql.DriverManager");
      Connection cnext=(Connection)DriverManager.getConnection("jdbc:Mysql://localhost:3306/quiz","root","root");
      Statement snext=(Statement)cnext.createStatement();
      String qnext="select max(qnu) from quiz where qid='"+QIDS.getSelectedItem().toString()+"';";
      ResultSet rnext=snext.executeQuery(qnext);
         if(rnext.next())
          {
             qmax=rnext.getInt("max(qnu)");
          }
      }  
      catch(ClassNotFoundException | SQLException e)
      {
       JOptionPane.showMessageDialog(this,e);
      }  
      
      
      
   if(quesno==qmax) // checking if current question is the last one
   {    
    JOptionPane.showMessageDialog(this,"You have reached the end of the quiz. Please click on submit");
   }    
   else//checking if the current question is not the last one
   { 
        try
        {
        Class.forName("java.sql.DriverManager");
        Connection cverify=(Connection)DriverManager.getConnection("jdbc:Mysql://localhost:3306/quiz","root","root");
        Statement sverify=(Statement)cverify.createStatement();
        String qverify="select correct from quiz where qid='"+QIDS.getSelectedItem().toString()+"' and qnu="+quesno+";";
        ResultSet rverify=sverify.executeQuery(qverify);
               if(rverify.next())
                 {
                  correcta=rverify.getString("correct");
                 }
        }
        catch(  ClassNotFoundException | SQLException e)
         {
          JOptionPane.showMessageDialog(this,e);
         }
        
        choice=getChoice();
        if(choice.equals(correcta))
        {
        score=score+1;
        //System.out.println(""+score);
        }
        
        quesno=Integer.parseInt(QNUM.getText());
        quesno=quesno+1;
        
        try
        {
        Class.forName("java.sql.DriverManager");
        Connection cprint=(Connection)DriverManager.getConnection("jdbc:Mysql://localhost:3306/quiz","root","root");
        Statement sprint=(Statement)cprint.createStatement();
        String qprint="select qnu,question,a,b,c,d from quiz where qnu="+quesno+" and qid='"+QIDS.getSelectedItem().toString()+"';";
        ResultSet rprint=sprint.executeQuery(qprint);
             if(rprint.next())
             {
                QNUM.setText(""+rprint.getInt("qnu"));
                QUES.setText(rprint.getString("question"));
                OPTA.setText(rprint.getString("a"));
                OPTB.setText(rprint.getString("b"));
                OPTC.setText(rprint.getString("c"));
                OPTD.setText(rprint.getString("d"));
             }
        
        }
        catch(  ClassNotFoundException | SQLException e)   
        {
        JOptionPane.showMessageDialog(this,e);
        }
          
   }
}
else //if quiz is not active, displaying appropriate eorror message
{
JOptionPane.showMessageDialog(this,"Quiz has not yet started");
}   
        
    }//GEN-LAST:event_NEXTMouseClicked

    private void NEXTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NEXTMouseEntered
       NEXT.setBackground(new Color(89,120,224));
    }//GEN-LAST:event_NEXTMouseEntered

    private void NEXTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NEXTMouseExited
  NEXT.setBackground(new Color(6,18,111));
    }//GEN-LAST:event_NEXTMouseExited

    private void STARTQMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_STARTQMouseEntered
STARTQ.setBackground(new Color(89,120,224)); 
        // TODO add your handling code here:
    }//GEN-LAST:event_STARTQMouseEntered

    private void STARTQMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_STARTQMouseExited
STARTQ.setBackground(new Color(6,18,111));        // TODO add your handling code here:
    }//GEN-LAST:event_STARTQMouseExited

    private void STARTQMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_STARTQMouseClicked
if(qstatus==0)
{
QIDS.setEnabled(false);
try
{
Class.forName("java.sql.DriverManager");
Connection ctest=(Connection)DriverManager.getConnection("jdbc:Mysql://localhost:3306/quiz","root","root");
Statement stest=(Statement)ctest.createStatement();
String qtest="select qnu,question,a,b,c,d from quiz where qnu=1 and qid='"+QIDS.getSelectedItem().toString()+"';";
ResultSet rtest=stest.executeQuery(qtest);
if(rtest.next())
{
quesno=rtest.getInt("qnu");
QNUM.setText(""+rtest.getInt("qnu"));
QUES.setText(rtest.getString("question"));
OPTA.setText(rtest.getString("a"));
OPTB.setText(rtest.getString("b"));
OPTC.setText(rtest.getString("c"));
OPTD.setText(rtest.getString("d"));
}
qstatus=1;
score=0;
quesno=1;
correcta="";
}
catch(  ClassNotFoundException | SQLException e)
{
JOptionPane.showMessageDialog(this,e);
}
}
else
{
    JOptionPane.showMessageDialog(this,"A Quiz is already active.Please finish the current quiz.");
    
}

        // TODO add your handling code here:
    }//GEN-LAST:event_STARTQMouseClicked

    private void SBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SBActionPerformed

    private void VSTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VSTMouseClicked
       
    }//GEN-LAST:event_VSTMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard_S.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard_S.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard_S.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard_S.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Dashboard_S().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CNP;
    private javax.swing.JTextField CNU;
    private javax.swing.JTextField CP;
    private javax.swing.JTextField CU;
    private javax.swing.JPanel Home;
    private javax.swing.JPanel LG;
    private javax.swing.JPanel NEXT;
    private javax.swing.JTextField NP;
    private javax.swing.JTextField NU;
    private javax.swing.JTextField OPTA;
    private javax.swing.JTextField OPTB;
    private javax.swing.JTextField OPTC;
    private javax.swing.JTextField OPTD;
    private javax.swing.JPanel Parent;
    private javax.swing.JComboBox<String> QIDS;
    private javax.swing.JTextField QNUM;
    private javax.swing.JTextField QUES;
    private javax.swing.JRadioButton SA;
    private javax.swing.JRadioButton SB;
    private javax.swing.JRadioButton SC;
    private javax.swing.JRadioButton SD;
    private javax.swing.JPanel SETTING;
    private javax.swing.JPanel STARTQ;
    private javax.swing.JPanel SUBMIT;
    private javax.swing.JPanel Settings;
    private javax.swing.JPanel Settings1;
    public static javax.swing.JLabel Sname;
    private javax.swing.JPanel Submitp;
    private javax.swing.JPanel Submitu;
    private javax.swing.JPanel TT;
    private javax.swing.JPanel TakeTest;
    private javax.swing.JPanel Take_Test;
    public static javax.swing.JLabel UID;
    private javax.swing.JPanel VS;
    private javax.swing.JTable VST;
    private javax.swing.JPanel View_Scores;
    private javax.swing.JPanel View_Scr;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JPanel sidepane;
    private javax.swing.JPanel upper_panel;
    // End of variables declaration//GEN-END:variables
}
