
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Riddho
 */
public class Dashboard_T extends javax.swing.JFrame {

    
    /**
     * Creates new form Dashboard_T
     */
    
    public int status;
    public String uid;
    public String qid,tid,question,a,b,c,d,correct,corr;
    public int qnu,qno;
    public int flag1,flag2,flag4;
    public int flag3=0;
    public int row,row1,row2;
    public Dashboard_T() 
    {
     initComponents();
    }
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        sidepane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Tname = new javax.swing.JLabel();
        UID = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Home = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CT = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        UP = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        SETTING = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        LG = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        upper_panel = new javax.swing.JPanel();
        Parent = new javax.swing.JPanel();
        home = new javax.swing.JPanel();
        View_Scr = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        SCT = new javax.swing.JTable();
        jLabel26 = new javax.swing.JLabel();
        Settings = new javax.swing.JPanel();
        Settings1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        CP = new javax.swing.JTextField();
        NP = new javax.swing.JTextField();
        CNP = new javax.swing.JTextField();
        Submitp = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        CU = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        NU = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        CNU = new javax.swing.JTextField();
        Submitu = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        VU = new javax.swing.JPanel();
        View_Update = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel52 = new javax.swing.JLabel();
        VQuestion = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        OpA = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        OpC = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        OpB = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        OpD = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        VCA = new javax.swing.JRadioButton();
        VCB = new javax.swing.JRadioButton();
        VCC = new javax.swing.JRadioButton();
        VCD = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        UPDATE = new javax.swing.JPanel();
        jLabel59 = new javax.swing.JLabel();
        Create = new javax.swing.JPanel();
        CreateTest = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        QID = new javax.swing.JTextField();
        QNU = new javax.swing.JTextField();
        Question = new javax.swing.JTextField();
        SQ = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        A = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        B = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        C = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        D = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        CA = new javax.swing.JRadioButton();
        CB = new javax.swing.JRadioButton();
        CC = new javax.swing.JRadioButton();
        CD = new javax.swing.JRadioButton();
        ADD = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(930, 530));

        sidepane.setBackground(new java.awt.Color(54, 33, 89));
        sidepane.setPreferredSize(new java.awt.Dimension(210, 530));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_teacher_100px.png"))); // NOI18N

        Tname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Tname.setForeground(new java.awt.Color(255, 255, 255));
        Tname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tname.setText("S.Gouthaman");

        UID.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        UID.setForeground(new java.awt.Color(255, 255, 255));
        UID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UID.setText("T100");

        Home.setBackground(new java.awt.Color(54, 33, 89));
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HomeMouseExited(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_home_30px.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Home");

        javax.swing.GroupLayout HomeLayout = new javax.swing.GroupLayout(Home);
        Home.setLayout(HomeLayout);
        HomeLayout.setHorizontalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HomeLayout.setVerticalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        CT.setBackground(new java.awt.Color(54, 33, 89));
        CT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CTMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CTMouseExited(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_test_passed_30px.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Create Test");

        javax.swing.GroupLayout CTLayout = new javax.swing.GroupLayout(CT);
        CT.setLayout(CTLayout);
        CTLayout.setHorizontalGroup(
            CTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CTLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CTLayout.setVerticalGroup(
            CTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        UP.setBackground(new java.awt.Color(54, 33, 89));
        UP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UPMouseExited(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_update_file_30px_1.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("View/Update Test");

        javax.swing.GroupLayout UPLayout = new javax.swing.GroupLayout(UP);
        UP.setLayout(UPLayout);
        UPLayout.setHorizontalGroup(
            UPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UPLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        UPLayout.setVerticalGroup(
            UPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        SETTING.setBackground(new java.awt.Color(54, 33, 89));
        SETTING.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SETTINGMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SETTINGMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SETTINGMouseExited(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_settings_30px.png"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Settings");

        javax.swing.GroupLayout SETTINGLayout = new javax.swing.GroupLayout(SETTING);
        SETTING.setLayout(SETTINGLayout);
        SETTINGLayout.setHorizontalGroup(
            SETTINGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SETTINGLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SETTINGLayout.setVerticalGroup(
            SETTINGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        LG.setBackground(new java.awt.Color(54, 33, 89));
        LG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LGMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LGMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LGMouseExited(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_exit_30px.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Logout");

        javax.swing.GroupLayout LGLayout = new javax.swing.GroupLayout(LG);
        LG.setLayout(LGLayout);
        LGLayout.setHorizontalGroup(
            LGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LGLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LGLayout.setVerticalGroup(
            LGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout sidepaneLayout = new javax.swing.GroupLayout(sidepane);
        sidepane.setLayout(sidepaneLayout);
        sidepaneLayout.setHorizontalGroup(
            sidepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(CT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(UP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(SETTING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sidepaneLayout.createSequentialGroup()
                .addGroup(sidepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidepaneLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(sidepaneLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
            .addComponent(Tname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(UID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sidepaneLayout.setVerticalGroup(
            sidepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidepaneLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Tname)
                .addGap(0, 0, 0)
                .addComponent(UID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(UP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SETTING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        upper_panel.setBackground(new java.awt.Color(54, 33, 89));
        upper_panel.setPreferredSize(new java.awt.Dimension(720, 16));

        javax.swing.GroupLayout upper_panelLayout = new javax.swing.GroupLayout(upper_panel);
        upper_panel.setLayout(upper_panelLayout);
        upper_panelLayout.setHorizontalGroup(
            upper_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        upper_panelLayout.setVerticalGroup(
            upper_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );

        Parent.setPreferredSize(new java.awt.Dimension(720, 514));
        Parent.setLayout(new java.awt.CardLayout());

        home.setBackground(new java.awt.Color(153, 255, 153));
        home.setPreferredSize(new java.awt.Dimension(720, 514));

        jLabel50.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(54, 33, 89));
        jLabel50.setText("Home");

        SCT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SCT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "QuizID", "Student ID", "Student Name", "Score"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        SCT.getTableHeader().setReorderingAllowed(false);
        SCT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SCTMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(SCT);

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(54, 33, 89));
        jLabel26.setText("Student's Results for the Created Tests are given below:");

        javax.swing.GroupLayout View_ScrLayout = new javax.swing.GroupLayout(View_Scr);
        View_Scr.setLayout(View_ScrLayout);
        View_ScrLayout.setHorizontalGroup(
            View_ScrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(View_ScrLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel50)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(View_ScrLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, View_ScrLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator6)
                .addGap(68, 68, 68))
            .addGroup(View_ScrLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        View_ScrLayout.setVerticalGroup(
            View_ScrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(View_ScrLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jLabel50)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel26)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout homeLayout = new javax.swing.GroupLayout(home);
        home.setLayout(homeLayout);
        homeLayout.setHorizontalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
            .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(View_Scr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        homeLayout.setVerticalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 539, Short.MAX_VALUE)
            .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(View_Scr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Parent.add(home, "card2");

        Settings.setPreferredSize(new java.awt.Dimension(720, 514));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(54, 33, 89));
        jLabel9.setText("Settings");

        jPanel1.setBackground(new java.awt.Color(54, 33, 89));
        jPanel1.setForeground(new java.awt.Color(54, 33, 89));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_lock_25px_1.png"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("CHANGE PASSWORD");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(54, 33, 89));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_user_shield_25px_1.png"))); // NOI18N

        jLabel16.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("CHANGE USERID");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(54, 33, 89));
        jLabel17.setText("Current Password:");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(54, 33, 89));
        jLabel18.setText("New Password:");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(54, 33, 89));
        jLabel19.setText("Confirm New Password:");

        Submitp.setBackground(new java.awt.Color(54, 33, 89));
        Submitp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SubmitpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SubmitpMouseExited(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Submit");

        javax.swing.GroupLayout SubmitpLayout = new javax.swing.GroupLayout(Submitp);
        Submitp.setLayout(SubmitpLayout);
        SubmitpLayout.setHorizontalGroup(
            SubmitpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        SubmitpLayout.setVerticalGroup(
            SubmitpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(54, 33, 89));
        jLabel21.setText("Current UserID:");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(54, 33, 89));
        jLabel22.setText("New UserID:");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(54, 33, 89));
        jLabel23.setText("Confirm New UserID:");

        Submitu.setBackground(new java.awt.Color(54, 33, 89));
        Submitu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmituMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SubmituMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SubmituMouseExited(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Submit");

        javax.swing.GroupLayout SubmituLayout = new javax.swing.GroupLayout(Submitu);
        Submitu.setLayout(SubmituLayout);
        SubmituLayout.setHorizontalGroup(
            SubmituLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        SubmituLayout.setVerticalGroup(
            SubmituLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Settings1Layout = new javax.swing.GroupLayout(Settings1);
        Settings1.setLayout(Settings1Layout);
        Settings1Layout.setHorizontalGroup(
            Settings1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Settings1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel9)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(Settings1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Settings1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(68, 68, 68))
            .addGroup(Settings1Layout.createSequentialGroup()
                .addGroup(Settings1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Settings1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(Settings1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(58, 58, 58)
                        .addGroup(Settings1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NP)
                            .addComponent(CNP, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                            .addComponent(CP, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(Settings1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(Settings1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Settings1Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(34, 34, 34)
                                .addComponent(CNU, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Settings1Layout.createSequentialGroup()
                                .addGroup(Settings1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel21))
                                .addGap(34, 34, 34)
                                .addGroup(Settings1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NU, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CU, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Settings1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Settings1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Settings1Layout.createSequentialGroup()
                        .addComponent(Submitp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(221, 221, 221))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Settings1Layout.createSequentialGroup()
                        .addComponent(Submitu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(222, 222, 222))))
        );
        Settings1Layout.setVerticalGroup(
            Settings1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Settings1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(Settings1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(CP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Settings1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(NP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(Settings1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(CNP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Submitp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(Settings1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(CU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Settings1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(18, 18, 18)
                .addGroup(Settings1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(CNU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Submitu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout SettingsLayout = new javax.swing.GroupLayout(Settings);
        Settings.setLayout(SettingsLayout);
        SettingsLayout.setHorizontalGroup(
            SettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
            .addGroup(SettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Settings1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SettingsLayout.setVerticalGroup(
            SettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 539, Short.MAX_VALUE)
            .addGroup(SettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Settings1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Parent.add(Settings, "card5");

        VU.setPreferredSize(new java.awt.Dimension(720, 514));

        jLabel49.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(54, 33, 89));
        jLabel49.setText("View/Update Quiz");

        jLabel52.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(54, 33, 89));
        jLabel52.setText("Question:");

        jLabel54.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(54, 33, 89));
        jLabel54.setText("A.");

        jLabel55.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(54, 33, 89));
        jLabel55.setText("B.");

        jLabel56.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(54, 33, 89));
        jLabel56.setText("C.");

        jLabel57.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(54, 33, 89));
        jLabel57.setText("D.");

        jLabel58.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(54, 33, 89));
        jLabel58.setText("Correct Option:");

        buttonGroup1.add(VCA);

        buttonGroup1.add(VCB);

        buttonGroup1.add(VCC);

        buttonGroup1.add(VCD);

        Table.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "QuizID", "Question", "Option A", "Option B", "Option C", "Option D", "Correct "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table.getTableHeader().setReorderingAllowed(false);
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Table);

        UPDATE.setBackground(new java.awt.Color(54, 33, 89));
        UPDATE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UPDATEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UPDATEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UPDATEMouseExited(evt);
            }
        });

        jLabel59.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel59.setText("Update");

        javax.swing.GroupLayout UPDATELayout = new javax.swing.GroupLayout(UPDATE);
        UPDATE.setLayout(UPDATELayout);
        UPDATELayout.setHorizontalGroup(
            UPDATELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel59, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
        );
        UPDATELayout.setVerticalGroup(
            UPDATELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel59, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout View_UpdateLayout = new javax.swing.GroupLayout(View_Update);
        View_Update.setLayout(View_UpdateLayout);
        View_UpdateLayout.setHorizontalGroup(
            View_UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(View_UpdateLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel49)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, View_UpdateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(View_UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator5)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, View_UpdateLayout.createSequentialGroup()
                        .addGroup(View_UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(View_UpdateLayout.createSequentialGroup()
                                .addComponent(jLabel52)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(VQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(View_UpdateLayout.createSequentialGroup()
                                .addGroup(View_UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(View_UpdateLayout.createSequentialGroup()
                                        .addComponent(jLabel58)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(VCA))
                                    .addGroup(View_UpdateLayout.createSequentialGroup()
                                        .addComponent(jLabel54)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(OpA, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(61, 61, 61)
                                .addGroup(View_UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(View_UpdateLayout.createSequentialGroup()
                                        .addComponent(jLabel55)
                                        .addGap(14, 14, 14)
                                        .addComponent(OpB, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(VCB))
                                .addGap(79, 79, 79)
                                .addGroup(View_UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(View_UpdateLayout.createSequentialGroup()
                                        .addComponent(jLabel56)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(OpC, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(VCC))
                                .addGap(55, 55, 55)
                                .addGroup(View_UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(View_UpdateLayout.createSequentialGroup()
                                        .addComponent(jLabel57)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(OpD, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(VCD))))
                        .addGap(0, 3, Short.MAX_VALUE)))
                .addGap(68, 68, 68))
            .addGroup(View_UpdateLayout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(UPDATE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(View_UpdateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        View_UpdateLayout.setVerticalGroup(
            View_UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(View_UpdateLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel49)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(View_UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel52)
                    .addComponent(VQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(View_UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel54)
                    .addComponent(OpA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OpD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OpC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OpB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel55)
                    .addComponent(jLabel56)
                    .addComponent(jLabel57))
                .addGap(28, 28, 28)
                .addGroup(View_UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel58)
                    .addComponent(VCA)
                    .addComponent(VCB)
                    .addComponent(VCC)
                    .addComponent(VCD))
                .addGap(18, 18, 18)
                .addComponent(UPDATE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout VULayout = new javax.swing.GroupLayout(VU);
        VU.setLayout(VULayout);
        VULayout.setHorizontalGroup(
            VULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
            .addGroup(VULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(View_Update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        VULayout.setVerticalGroup(
            VULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 514, Short.MAX_VALUE)
            .addGroup(VULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(View_Update, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Parent.add(VU, "card4");

        Create.setBackground(new java.awt.Color(153, 255, 255));
        Create.setPreferredSize(new java.awt.Dimension(720, 514));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(54, 33, 89));
        jLabel25.setText("Create Test");

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(54, 33, 89));
        jLabel30.setText("Quiz ID:");

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(54, 33, 89));
        jLabel31.setText("Question No.");

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(54, 33, 89));
        jLabel32.setText("Question:");

        SQ.setBackground(new java.awt.Color(54, 33, 89));
        SQ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SQMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SQMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SQMouseExited(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("Save Quiz");
        jLabel33.setPreferredSize(new java.awt.Dimension(119, 28));

        javax.swing.GroupLayout SQLayout = new javax.swing.GroupLayout(SQ);
        SQ.setLayout(SQLayout);
        SQLayout.setHorizontalGroup(
            SQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SQLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        SQLayout.setVerticalGroup(
            SQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(54, 33, 89));
        jLabel34.setText("A.");

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(54, 33, 89));
        jLabel35.setText("B.");

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(54, 33, 89));
        jLabel36.setText("C.");

        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(54, 33, 89));
        jLabel38.setText("D.");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(54, 33, 89));
        jLabel27.setText("Correct Option:");

        buttonGroup1.add(CA);

        buttonGroup1.add(CB);

        buttonGroup1.add(CC);

        buttonGroup1.add(CD);

        ADD.setBackground(new java.awt.Color(54, 33, 89));
        ADD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ADDMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ADDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ADDMouseExited(evt);
            }
        });

        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("Add Question");

        javax.swing.GroupLayout ADDLayout = new javax.swing.GroupLayout(ADD);
        ADD.setLayout(ADDLayout);
        ADDLayout.setHorizontalGroup(
            ADDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel39, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
        );
        ADDLayout.setVerticalGroup(
            ADDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel39, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout CreateTestLayout = new javax.swing.GroupLayout(CreateTest);
        CreateTest.setLayout(CreateTestLayout);
        CreateTestLayout.setHorizontalGroup(
            CreateTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateTestLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel25)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreateTestLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CreateTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(CreateTestLayout.createSequentialGroup()
                        .addGroup(CreateTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CreateTestLayout.createSequentialGroup()
                                .addGroup(CreateTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel32)
                                    .addComponent(jLabel31)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel34)
                                    .addComponent(jLabel35)
                                    .addComponent(jLabel36))
                                .addGap(26, 26, 26)
                                .addGroup(CreateTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(QNU, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Question, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(QID, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(CreateTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(CD)
                                        .addGroup(CreateTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CreateTestLayout.createSequentialGroup()
                                                .addComponent(C, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                                                .addComponent(CC))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CreateTestLayout.createSequentialGroup()
                                                .addComponent(B, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(CB))
                                            .addGroup(CreateTestLayout.createSequentialGroup()
                                                .addComponent(A, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(CA))))))
                            .addGroup(CreateTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(CreateTestLayout.createSequentialGroup()
                                    .addComponent(jLabel38)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 491, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreateTestLayout.createSequentialGroup()
                                    .addGap(95, 95, 95)
                                    .addComponent(D, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreateTestLayout.createSequentialGroup()
                                    .addGap(124, 124, 124)
                                    .addComponent(ADD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(SQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(0, 20, Short.MAX_VALUE))
                    .addComponent(jSeparator3))
                .addGap(68, 68, 68))
        );
        CreateTestLayout.setVerticalGroup(
            CreateTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateTestLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(CreateTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(QID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(CreateTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(QNU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(CreateTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(CreateTestLayout.createSequentialGroup()
                        .addGroup(CreateTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Question, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel27)
                        .addGap(19, 19, 19)
                        .addGroup(CreateTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CA)
                            .addGroup(CreateTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel34)
                                .addComponent(A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31)
                        .addGroup(CreateTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CB)
                            .addGroup(CreateTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel35)
                                .addComponent(B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(36, 36, 36)
                        .addGroup(CreateTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CC)
                            .addGroup(CreateTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel36)
                                .addComponent(C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34)
                        .addGroup(CreateTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel38)
                            .addComponent(D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(CD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(CreateTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ADD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout CreateLayout = new javax.swing.GroupLayout(Create);
        Create.setLayout(CreateLayout);
        CreateLayout.setHorizontalGroup(
            CreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
            .addGroup(CreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(CreateTest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CreateLayout.setVerticalGroup(
            CreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 539, Short.MAX_VALUE)
            .addGroup(CreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(CreateTest, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Parent.add(Create, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidepane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(upper_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Parent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidepane, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(upper_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Parent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
public void ClearAll(){
    
VQuestion.setText("");
OpA.setText("");
OpB.setText("");
OpC.setText("");
OpD.setText("");
VCA.setSelected(false);
VCB.setSelected(false);
VCC.setSelected(false);
VCD.setSelected(false);
Table.getSelectionModel().clearSelection();
CP.setText("");
NP.setText("");
CNP.setText("");
CU.setText("");
NU.setText("");
CNU.setText("");
QID.setText("");
Question.setText("");
A.setText("");
B.setText("");
C.setText("");
D.setText("");
CA.setText("");
CB.setText("");
CC.setText("");
CD.setText("");
Table.getSelectionModel().clearSelection();
}
public void fetch()
{
        try
        {
        Class.forName("java.sql.DriverManager");
        Connection cfetch=(Connection)DriverManager.getConnection("jdbc:Mysql://localhost:3306/quiz","root","root");
        Statement sfetch=(Statement)cfetch.createStatement();
        String fetch= "select qid 'QuizID',question 'Question', a 'Option A',b 'Option B',c 'Option C',d 'Option D',correct 'Correct' from quiz where tid='"+UID.getText()+"';";
        ResultSet rsfetch=sfetch.executeQuery(fetch);
        Table.setModel(DbUtils.resultSetToTableModel(rsfetch));
        }
        catch(ClassNotFoundException | SQLException e)
        {    
           
        JOptionPane.showMessageDialog(this,e);
        }
        
        
        
    }
public int getQno()
{
int rowSelected=Table.getSelectedRow();

try
{
Class.forName("java.sql.DriverManager");
Connection cget=(Connection)DriverManager.getConnection("jdbc:Mysql://localhost:3306/quiz","root","root");
Statement sget=(Statement)cget.createStatement();
String qget="select qnu from quiz where question='"+Table.getValueAt(rowSelected, 1).toString()+"';";
ResultSet rget=sget.executeQuery(qget);
if(rget.next())
{
    return rget.getInt("qnu");
}
}
catch(  ClassNotFoundException | SQLException e)
{
JOptionPane.showMessageDialog(this,e);

}


return 0;

}
public void scorefetch()
{
   try
  {
      Class.forName("java.sql.DriverManager");
     Connection cscorefetch=(Connection)DriverManager.getConnection("jdbc:Mysql://localhost:3306/quiz","root","root");
     Statement sscorefetch=(Statement)cscorefetch.createStatement();
     String qscorefetch="select qid 'QuizID',sid 'Student ID',studame 'Student Name',score 'Score' from scores where tid='"+UID.getText()+"';";
     ResultSet rscorefetch=sscorefetch.executeQuery(qscorefetch);
     SCT.setModel(DbUtils.resultSetToTableModel(rscorefetch));
   }   
   catch(ClassNotFoundException | SQLException e)
   {
   JOptionPane.showMessageDialog(this,e);
   }  
}
    private void HomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseEntered
        Home.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_HomeMouseEntered

    private void HomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseExited
   if(status!=1)
   {
    Home.setBackground(new Color(54,33,89));
   }
    }//GEN-LAST:event_HomeMouseExited

    private void CTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CTMouseEntered
        CT.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_CTMouseEntered

    private void CTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CTMouseExited
   if(status!=2)
        CT.setBackground(new Color(54,33,89));
    }//GEN-LAST:event_CTMouseExited

    private void UPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UPMouseEntered
        UP.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_UPMouseEntered

    private void UPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UPMouseExited
if(status!=3)
        UP.setBackground(new Color(54,33,89));
    }//GEN-LAST:event_UPMouseExited

    private void SETTINGMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SETTINGMouseEntered
        SETTING.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_SETTINGMouseEntered

    private void SETTINGMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SETTINGMouseExited
if(status!=4)
        SETTING.setBackground(new Color(54,33,89));
    }//GEN-LAST:event_SETTINGMouseExited

    private void LGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LGMouseClicked
int choice;
        choice = JOptionPane.showConfirmDialog(this,"Are you sure you want to log out ?");
        if(choice==0){
            dispose();
            Login lo=new Login();
            lo.show();
        }
    }//GEN-LAST:event_LGMouseClicked

    private void LGMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LGMouseEntered
        LG.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_LGMouseEntered

    private void LGMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LGMouseExited
LG.setBackground(new Color(54,33,89));
    }//GEN-LAST:event_LGMouseExited

    private void SETTINGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SETTINGMouseClicked
status=4;
SETTING.setBackground(new Color(85,65,118));
UP.setBackground(new Color(54,33,89));
Home.setBackground(new Color(54,33,89));
CT.setBackground(new Color(54,33,89));
Parent.removeAll();
Parent.add(Settings);
Parent.repaint();
Parent.revalidate();
CP.setText("");
NP.setText("");
CNP.setText("");
CU.setText("");
NU.setText("");
CNU.setText("");
ClearAll();

    }//GEN-LAST:event_SETTINGMouseClicked

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
status =1;
Home.setBackground(new Color(85,65,118));
UP.setBackground(new Color(54,33,89));
SETTING.setBackground(new Color(54,33,89));
CT.setBackground(new Color(54,33,89));
Parent.removeAll();
Parent.add(home);
Parent.repaint();
Parent.revalidate();
scorefetch();
ClearAll();
    }//GEN-LAST:event_HomeMouseClicked

    private void UPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UPMouseClicked
status=3;
UP.setBackground(new Color(85,65,118));
Home.setBackground(new Color(54,33,89));
SETTING.setBackground(new Color(54,33,89));
CT.setBackground(new Color(54,33,89));
Parent.removeAll();
Parent.add(VU);
Parent.repaint();
Parent.revalidate();
fetch();
ClearAll();
    }//GEN-LAST:event_UPMouseClicked

    private void CTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CTMouseClicked
status=2;
CT.setBackground(new Color(85,65,118));
Home.setBackground(new Color(54,33,89));
SETTING.setBackground(new Color(54,33,89));
UP.setBackground(new Color(54,33,89));
Parent.removeAll();
Parent.add(Create);
Parent.repaint();
Parent.revalidate(); 
qnu=1;
QNU.setText("1");
CA.setSelected(false);
CB.setSelected(false);
CC.setSelected(false);
CD.setSelected(false);
QID.setEditable(true);
QNU.setEditable(true);
QID.setText("");
Question.setText("");
A.setText("");
B.setText("");
C.setText("");
D.setText("");
ClearAll();
    }//GEN-LAST:event_CTMouseClicked

    private void SubmitpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitpMouseClicked
      flag2=1;
        uid=UID.getText();
        try {
          Class.forName("java.sql.DriverManager");
          Connection co=(Connection)DriverManager.getConnection("jdbc:Mysql://localhost:3306/quiz","root","root");
          Statement su=(Statement)co.createStatement();
          String q="select password from details where userid='"+uid+"';";
          ResultSet r1=su.executeQuery(q);
   if(r1.next())
   
       { 
             if(r1.getString(1).equals(CP.getText())==false)           
                     
                     {
              JOptionPane.showMessageDialog(this,"Current Password is incorrect");
              flag2=0;
                     
                     }
       
        }  
        } 
        catch(HeadlessException | ClassNotFoundException | SQLException e){
         JOptionPane.showMessageDialog(this,e);
        }
        
if(CP.getText().equals("") || NP.getText().equals("") || CNP.getText().equals(""))
{
    JOptionPane.showMessageDialog(this,"Missing details");
     flag2=0;
    
}
else if(NP.getText().equals(CNP.getText())==false)
{
    JOptionPane.showMessageDialog(this,"New passwords do not match");
     flag2=0;
    
}
if(flag2!=0)
{
 String np=NP.getText();   
 
    try {
    Class.forName("java.sql.DriverManager");
    Connection connection=(Connection)DriverManager.getConnection("jdbc:Mysql://localhost:3306/quiz","root","root");
    Statement statement=(Statement)connection.createStatement();
    String q2="update details set password='"+np+"'where userid='"+uid+"';";
    statement.executeUpdate(q2);
    
    JOptionPane.showMessageDialog(this,"Changes Saved");
    CP.setText("");
    NP.setText("");
   CNP.setText("");
}
    
catch(HeadlessException | ClassNotFoundException | SQLException e){
         JOptionPane.showMessageDialog(this,e);
        }
}
// TODO add your handling code here:
    }//GEN-LAST:event_SubmitpMouseClicked

    private void SubmituMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmituMouseClicked

flag2=1;        
String nu=NU.getText();

if(UID.getText().equals(CU.getText())==false)
{
     flag2=0;
JOptionPane.showMessageDialog(this,"Current UserId is incorrect");
}
if(CU.getText().equals("") || NU.getText().equals("") || CNU.getText().equals(""))
{
     flag2=0;
    JOptionPane.showMessageDialog(this,"Please ensure all fields are entered before submitting");  
}        
if(NU.getText().equals(CNU.getText())==false)
{
     flag2=0;
    JOptionPane.showMessageDialog(this,"New userid's do not match");
}
if( flag2!=0)
{
try {
    Class.forName("java.sql.DriverManager");
    Connection connection2=(Connection)DriverManager.getConnection("jdbc:Mysql://localhost:3306/quiz","root","root");
    Statement statement2=(Statement)connection2.createStatement();
    String q3="update details set userid='"+nu+"'where userid='"+CU.getText()+"';";
    statement2.executeUpdate(q3);
    JOptionPane.showMessageDialog(this,"Changes Saved");
    UID.setText(nu);
    CU.setText("");
    NU.setText("");
   CNU.setText("");
}
    
catch(HeadlessException | ClassNotFoundException | SQLException e){
         JOptionPane.showMessageDialog(this,e);
        }
}        
    }//GEN-LAST:event_SubmituMouseClicked

    private void SubmitpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitpMouseEntered
Submitp.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_SubmitpMouseEntered

    private void SubmitpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitpMouseExited
Submitp.setBackground(new Color(54,33,89));        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitpMouseExited

    private void SubmituMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmituMouseEntered
Submitu.setBackground(new Color(85,65,118));  // TODO add your handling code here:
    }//GEN-LAST:event_SubmituMouseEntered

    private void SubmituMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmituMouseExited
Submitu.setBackground(new Color(54,33,89));         // TODO add your handling code here:
    }//GEN-LAST:event_SubmituMouseExited

    private void SQMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SQMouseClicked
if(flag1!=0)
{
JOptionPane.showMessageDialog(this,"Quiz has been saved.");
CA.setSelected(false);
CB.setSelected(false);
CC.setSelected(false);
CD.setSelected(false);
QID.setEditable(true);
QNU.setEditable(true);
QID.setText("");
QNU.setText("1");
Question.setText("");
A.setText("");
B.setText("");
C.setText("");
D.setText("");
}
else
{
JOptionPane.showMessageDialog(this,"Quiz could not be saved.");
}
    }//GEN-LAST:event_SQMouseClicked

    private void SQMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SQMouseEntered
SQ.setBackground(new Color(85,65,118));       // TODO add your handling code here:
    }//GEN-LAST:event_SQMouseEntered

    private void SQMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SQMouseExited
      SQ.setBackground(new Color(54,33,89));   // TODO add your handling code here:
    }//GEN-LAST:event_SQMouseExited

    private void ADDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADDMouseClicked
qid=QID.getText();
tid=UID.getText();
qnu=Integer.parseInt(QNU.getText());
question=Question.getText();
a=A.getText();
b=B.getText();
c=C.getText();
d=D.getText();
flag1=1;

if(CA.isSelected()==true){
    correct=A.getText();
}
else if(CB.isSelected()==true){
    correct=B.getText();
}
else if(CC.isSelected()==true){
    correct=C.getText();
}
else if(CD.isSelected()==true){
    correct=D.getText();
}
else
{
    //JOptionPane.showMessageDialog(this,"Please choose the correct option.");
    flag1=0;
}
if(QID.getText().equals("") || QNU.getText().equals("") || Question.getText().equals("") || A.getText().equals("") || B.getText().equals("") || C.getText().equals("") || D.getText().equals(""))
{
    //JOptionPane.showMessageDialog(this,"Please make sure all the fields are entered");
    flag1=0;
}
if(flag1!=0)
{
       try 
       {
          Class.forName("java.sql.DriverManager");
          Connection connection1=(Connection)DriverManager.getConnection("jdbc:Mysql://localhost:3306/quiz","root","root");
          Statement st=(Statement)connection1.createStatement();
          String check="select qid,qnu from quiz where qid='"+qid+"' and qnu="+qnu+";";
          String insert="insert into quiz values('"+qid+"','"+tid+"',"+qnu+",'"+question+"','"+a+"','"+b+"','"+c+"','"+d+"','"+correct+"');";
          ResultSet rcheck=st.executeQuery(check);
           if(rcheck.next())
          {
           JOptionPane.showMessageDialog(this,"Question No. for following quiz already exists. The next question number to be added shall be printed.");
          String max="select max(qnu) from quiz where qid='"+qid+"';";
          ResultSet rmax=st.executeQuery(max);
             if(rmax.next())
             {
             qnu=Integer.parseInt(rmax.getString(1));
             qnu=qnu+1;
             QNU.setText(""+qnu);
             } 
            } 
          else
          {
          st.execute(insert);
          JOptionPane.showMessageDialog(this,"Question has been added");
          QID.setEditable(false);
          QNU.setEditable(false);
          qnu=qnu+1;
          QNU.setText("1");
          Question.setText("");
          A.setText("");
          B.setText("");
          C.setText("");
          D.setText("");
          CA.setSelected(false);
          CB.setSelected(false);
          CC.setSelected(false);
          CD.setSelected(false);
           }
       }
        catch( HeadlessException | ClassNotFoundException | SQLException e)
         {
          JOptionPane.showMessageDialog(this,e);
          }
}
else
{
 JOptionPane.showMessageDialog(this,"Question could not be added. Make sure to fill all the details");
}
String questionumber=String.valueOf(qnu);
QNU.setText(questionumber);
    }//GEN-LAST:event_ADDMouseClicked

    private void ADDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADDMouseEntered
        ADD.setBackground(new Color(85,65,118)); 
    }//GEN-LAST:event_ADDMouseEntered

    private void ADDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADDMouseExited
         ADD.setBackground(new Color(54,33,89)); 
    }//GEN-LAST:event_ADDMouseExited

    private void UPDATEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UPDATEMouseClicked
if(VQuestion.getText().equals("") || OpA.getText().equals("") || OpB.getText().equals("") || OpC.getText().equals("") || OpD.getText().equals("")           )
{        
    JOptionPane.showMessageDialog(this,"Make sure all the details have been entered");
}       
else
{  
row2=Table.getSelectedRow();
qno=getQno();
if(VCA.isSelected()==true)
{
corr=OpA.getText();
}
if(VCB.isSelected()==true)
{
corr=OpB.getText();
}
if(VCC.isSelected()==true)
{
corr=OpC.getText();
}
if(VCD.isSelected()==true)
{
corr=OpD.getText();
}
try
{
Class.forName("java.sql.DriverManager");
Connection cupdate=(Connection)DriverManager.getConnection("jdbc:Mysql://localhost:3306/quiz","root","root");
Statement supdate=(Statement)cupdate.createStatement();
String qupdate="update quiz set question='"+VQuestion.getText()+"',a='"+OpA.getText()+"',b='"+OpB.getText()+"',c='"+OpC.getText()+"',d='"+OpD.getText()+"',correct='"+corr+"' where qnu="+qno+" and qid='"+Table.getValueAt(row,0).toString()+"';";
supdate.executeUpdate(qupdate);
JOptionPane.showMessageDialog(this,"Updated Successfully");
fetch();
}
catch(  HeadlessException | ClassNotFoundException | SQLException e)
{
JOptionPane.showMessageDialog(this,e);
}
    }//GEN-LAST:event_UPDATEMouseClicked
    }
    private void UPDATEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UPDATEMouseEntered
UPDATE.setBackground(new Color(85,65,118));        // TODO add your handling code here:
    }//GEN-LAST:event_UPDATEMouseEntered

    private void UPDATEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UPDATEMouseExited
UPDATE.setBackground(new Color(54,33,89));     // TODO add your handling code here:
    }//GEN-LAST:event_UPDATEMouseExited

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
row=Table.getSelectedRow();
VQuestion.setText(Table.getValueAt(row,1).toString());
OpA.setText(Table.getValueAt(row,2).toString());OpB.setText(Table.getModel().getValueAt(row,3).toString());
OpC.setText(Table.getValueAt(row,4).toString());
OpD.setText(Table.getValueAt(row,5).toString());
String crrct=Table.getValueAt(row,6).toString();
if(crrct.equals(OpA.getText())==true)
{
VCA.setSelected(true);
}
if(crrct.equals(OpB.getText())==true)
{
VCB.setSelected(true);
}
if(crrct.equals(OpC.getText())==true)
{
VCC.setSelected(true);
}
if(crrct.equals(OpD.getText())==true)
{
VCD.setSelected(true);
}
    }//GEN-LAST:event_TableMouseClicked

    private void SCTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SCTMouseClicked

    }//GEN-LAST:event_SCTMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard_T.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard_T.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard_T.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard_T.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Dashboard_T().setVisible(true);
      
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField A;
    private javax.swing.JPanel ADD;
    private javax.swing.JTextField B;
    private javax.swing.JTextField C;
    private javax.swing.JRadioButton CA;
    private javax.swing.JRadioButton CB;
    private javax.swing.JRadioButton CC;
    private javax.swing.JRadioButton CD;
    private javax.swing.JTextField CNP;
    private javax.swing.JTextField CNU;
    private javax.swing.JTextField CP;
    private javax.swing.JPanel CT;
    private javax.swing.JTextField CU;
    private javax.swing.JPanel Create;
    private javax.swing.JPanel CreateTest;
    private javax.swing.JTextField D;
    private javax.swing.JPanel Home;
    private javax.swing.JPanel LG;
    private javax.swing.JTextField NP;
    private javax.swing.JTextField NU;
    private javax.swing.JTextField OpA;
    private javax.swing.JTextField OpB;
    private javax.swing.JTextField OpC;
    private javax.swing.JTextField OpD;
    private javax.swing.JPanel Parent;
    private javax.swing.JTextField QID;
    private javax.swing.JTextField QNU;
    private javax.swing.JTextField Question;
    private javax.swing.JTable SCT;
    private javax.swing.JPanel SETTING;
    private javax.swing.JPanel SQ;
    private javax.swing.JPanel Settings;
    private javax.swing.JPanel Settings1;
    private javax.swing.JPanel Submitp;
    private javax.swing.JPanel Submitu;
    private javax.swing.JTable Table;
    public static javax.swing.JLabel Tname;
    public static javax.swing.JLabel UID;
    private javax.swing.JPanel UP;
    private javax.swing.JPanel UPDATE;
    private javax.swing.JRadioButton VCA;
    private javax.swing.JRadioButton VCB;
    private javax.swing.JRadioButton VCC;
    private javax.swing.JRadioButton VCD;
    private javax.swing.JTextField VQuestion;
    private javax.swing.JPanel VU;
    private javax.swing.JPanel View_Scr;
    private javax.swing.JPanel View_Update;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JPanel sidepane;
    private javax.swing.JPanel upper_panel;
    // End of variables declaration//GEN-END:variables

    }
